- addon/services/cookies.js
This enables options like `path`, `expires` etc.
> allow setting cookie options

- addon/services/cookies.js
- tests/unit/services/cookies-test.js
@marcoow You forgot something. :smile:
> Fix request in _filterCachedFastbootCookies

- tests/unit/services/cookies-test.js
This cleans up the cookie service specs
> Specs Cleanup

- addon/services/cookies.js
- package.json
- tests/unit/services/cookies-test.js
Update the ember-cli-fastboot dependency to use the latest version (currently 1.0.0-beta.4).
This also fixes #21
> Fastboot 1.0

- package.json
> Update "ember-cli-mocha" to v0.14.1

- package.json
> chore(package): update ember-cli-mocha to version 0.14.4

- README.md
> chore: document `maxAge` option.

- tests/unit/services/cookies-test.js
I actually misread the code and couldn't see how options would be appended to the cookie. So I wrote the test and realised my mistake. Anyways I thought I'd submit the PR just in case as a regression test.
> test: ensure multiple options are added to the cookie

- addon/services/cookies.js
- tests/dummy/app/app.js
- tests/dummy/app/controllers/index.js
- tests/dummy/app/router.js
- tests/helpers/destroy-app.js
- tests/helpers/module-for-acceptance.js
- tests/helpers/start-app.js
- tests/unit/services/cookies-test.js
see https://github.com/ember-cli/ember-rfc176-data
> Use "New Module Imports"

- package.json
- yarn.lock
Closes https://github.com/simplabs/ember-cookies/pull/138
> Use caret constraint for `ember-cli-babel` dependency

- addon-test-support/ember-cookies/clear-all-cookies.js
- index.js
- tests/unit/services/cookies-test.js
> feat(test-helper): Clear all cookies

- .travis.yml
- testem.js
as requested in https://github.com/simplabs/ember-test-selectors/pull/169#issuecomment-359356038
see ember-cli/ember-cli#7566
> testem: Use `--no-sandbox` on TravisCI

- README.md
This PR updates the example to use the "new" module syntax import.
> Update README.md example to use module syntax import

- .travis.yml
- ember-cli-build.js
> use let instead of var

- package.json
> chore(package): update ember-source to version 3.1.1

- addon/services/cookies.js
i think we should update too ember-simple-auth
ref #203
> Fix warning use of merge has been deprecated.

- addon/services/cookies.js
- tests/unit/services/cookies-test.js
> support cookies with "=" in the value

- addon-test-support/ember-cookies/clear-all-cookies.js
- addon/services/cookies.js
- addon/utils/serialize-cookie.js
- tests/unit/clear-all-cookies-test.js
> Support receiving options for clearAllCookies test helper

- .github/workflows/ci.yml
> CI: Run `lint:js` in dedicated job

- .eslintrc.js
- package.json
- yarn.lock
for decorator support and optional chaining
> ESLint: Use `babel-eslint` parser

- .eslintrc.js
- addon/services/cookies.js
- tests/dummy/app/controllers/index.js
> Use regular property access instead of `get()` calls

- package.json
- tests/unit/services/cookies-test.js
- yarn.lock
> Bump `eslint-plugin-qunit` to v7 and fix errors

- renovate.json
> ci(renovate): add renovate config

- renovate.json
Requires https://github.com/mainmatter/renovate-config/pull/17
> chore(deps): use common Mainmatter config for addons

- .github/workflows/release.yml
- packages/ember-cookies/package.json
Aligns with https://github.com/mainmatter/ember-simple-auth/blob/master/.github/workflows/release.yml
> chore(release): use volta setup for release workflow

- README.md
- packages/ember-cookies/eslint.config.mjs
- packages/ember-cookies/src/services/cookies.ts
- packages/test-app/app/controllers/index.ts
- Document typescript example
- Add `#read()` signature overload
> doc(typescript): add usage example
