mainmatter/ember-cookies

addon/services/cookies.js, package.json
This uses the fastboot service's isFastBoot property to detect whether the app is currently running in FastBoot context rather than relying on the presence of a private property in the service.
=> better fastboot detection

README.md, addon/services/cookies.js, node-tests/acceptance/cookie-access-test.js, tests/unit/services/cookies-test.js
This corrects all occurences of `fastboot` or `Fastboot` to `fastBoot` or `FastBoot` instead.
=> it's FastBoot with a capital B

addon/services/cookies.js, package.json, tests/unit/services/cookies-test.js
@marcoow I updated ember-cookies to use `FastBootRequest` and `FastBootResponse`.
=> Update to use the FastBoot service's public API

README.md, addon/services/cookies.js, tests/unit/services/cookies-test.js
Came across the need for this ability while using the library in my project.
I wasn't sure how you wanted me to update `CHANGELOG.md` to reflect the new feature. Let me know what your style is and I'll add that too!
=> Add clear method to clear existing cookies

addon/services/cookies.js, package.json
This PR removes the `ember-lodash` dependency. Importing all of lodash just for these two functions seems a bit wasteful to me unless you're already using it anyway.
=> Remove "ember-lodash" dependency

addon/services/cookies.js, tests/unit/services/cookies-test.js
Handling of cached FastBoot cookies was broken when the cache was empty. The FastBoot cookies actually have the form `{ name: value, … }` while our cache has the form `{ name: { value: value, options. {…} }, … }` which was wrongly stubbed in the tests.
=> Fix FastBoot cookie cache handling

addon/services/cookies.js, node-tests/acceptance/cookie-access-test.js, package.json, tests/dummy/config/environment.js, tests/unit/services/cookies-test.js
**TL;DR**
- Fix host.
- Upgrade `ember-cli-fastboot`.
- Add hostWhitelist to dummy app config.
- Add domain to dummy app test on writing cookies.
**Details**
When writing a cookie with domain, in fastboot land, it breaks
It seems that we cannot use  ES6 deconstruct to get host from `fastboot.request` it was returning an object containing: 
```js
Descriptor {
isDescriptor: true,
_getter: [Function],
_dependentKeys: undefined,
_suspended: undefined,
_meta: undefined,
_volatile: false,
_readOnly: false }
```
However, when we call `this.get('_fastBoot.request.host')` it returns what is expected.
It would be nice to have tests for the `write` cookies with domain, but not sure how. I would love some guidance on that.
=> Fix usage of fastboot host

addon/services/cookies.js, tests/unit/services/cookies-test.js
In some browsers we're seeing invalid cookies kill our application.
I don't really like guarding for things like this, but I'd rather guard
than have a flaky application. Thoughts?
We've seen this behavior on both IE11 and Edge on Windows 7 and Windows
10.
=> Fixes invalid cookies

README.md, addon/services/cookies.js, tests/unit/services/cookies-test.js
This PR follows up @t4t5's work on https://github.com/simplabs/ember-cookies/pull/28.
It allows the `clear` method to take some options.
=> Allow options when deleting cookies

README.md
Adds the optional `options` arg to `clear()` in the README
=> Add options to args for clear() in README

.travis.yml
"stable" is 8 now, which seems to cause some issues somewhere. This should hopefully fix the CI builds.
=> CI: Run on Node 4 and 6

tests/unit/services/cookies-test.js
- Previously accidentally using setProperties, so the expectations were not being run in the browser write cookies tests.
closes #73
=> fix: set fake document on service in tests

addon/services/cookies.js, tests/unit/services/cookies-test.js
FastBoot recently changed the string value of the `protocol` property for HTTPS requests from `'https'` to `'https:'` which breaks HTTPS detection in ember-cookies. This PR changes that detection so that it treats both `'https'` and `'https:'` as HTTPS and thus works correctly with new and old FastBoot versions.
closes #131
=> work with both "https" and "https:" protocols

README.md, addon/services/cookies.js, tests/unit/services/cookies-test.js
This commit adds a new `encodeValue` option to ember-cookies. I made it `true` by default to match current behavior. When it is set to `false`, it bypasses encoding the value of the cookie, in case that behavior is not desired by the user.
I personally have a scenario where I don't want the cookie to be encoded automatically, hence making this change.
=> Add useRawValue option to avoid encoding/decoding

addon/services/cookies.js
Closes #145 
This just does the classic Ember.assign fallback if Object.assign isn't defined (i.e. in IE ;)
=> Fix Object.assign error in IE11

README.md, addon/services/cookies.js, tests/unit/services/cookies-test.js
It is currently not possible to check whether a cookie exists at all (even with a falsy value like `cookie=`). That is due to the fact that we [filter the cookies (at least document cookies) to only includes the ones where both key and value are present](https://github.com/simplabs/ember-cookies/blob/master/addon/services/cookies.js#L181).
This adds an `exists` method to the cookies service that behaves like this:
```js
document.cookie = 'test=';
$E.exists('test'); // returns true
```
=> Add method to check whether a cookie exists

addon/services/cookies.js
Read and write currently clone the options hash that comes in. Clear doesn't. Even though it doesn't have defaults, the cloning does prevent confusion when testing. Our application had an options hash we were passing into the `clear` method, and when we did, it would add on the `expires = new Date('1970-01-01')` to it. When we called `clear` again with the same options hash, it would fail because of the `assert` above (`assert('Expires, Max-Age, and raw options cannot be set when clearing cookies', isEmpty(options.expires) && isEmpty(options.maxAge) && isEmpty(options.raw));`).
=> Clone options hash to avoid mutating original options hash

addon/services/cookies.js, tests/unit/services/cookies-test.js
This fixes the FastBoot cookie caching logic so that we always read the request cookies now and merge them with the cache. Previously, when the cache was already populated, we would never read the request cookies again. As the cache is also populated when cookies are written (which is the main reason we need the cache as we cannot read written cookies again from anywhere), it was possible to run into a situation where the cache was populated by a write before anything had ever be read and then on the next read, the request cookies would be ignored (@joshkg describes that much better in #177).
closes #177
=> Fix Fastboot cookie caching

addon/services/cookies.js, tests/unit/services/cookies-test.js
There is currently no support for setting `httpOnly` on cookies in `write()`, with an explicit assert saying it's not useful.
While what it says is true and you won't be able to read them from inside Ember, there are still useful reasons you might want to set a httpOnly cookie, e.g. if it is generated by the client but only needs to be readable by a backend service/API.
(If you prefer to keep the assert, it could instead be an option like `yesReallyHttpOnly` passed into `write()` that causes it to allow writing one, I just need _some_ way to do it)
=> Allow setting httpOnly

addon/services/cookies.js, tests/unit/services/cookies-test.js
Currently, every time something calls write() a new Set-Cookie header gets added for fastboot. So if you do:
```
cookies.write('foo', 'value1');
cookies.write('foo', 'value2');
```
The response headers are sent as:
```
Set-Cookie: foo=value1
Set-Cookie: foo=value2
```
And all that is sent in the response back to the client/browser, which then ignores all but the last set for a given key.  ember-simple-auth in particular does several sets of the same key and ends up constantly sending multiple values for the same cookie.
This PR changes `write()` -> `_writeFastBootCookie(name, value)` to look for an existing `set-cookie` header for `name` and replace the existing entry's value with the new one if found, instead of always appending a new entry.
=> Send a given cookie name only once per fastboot response

addon/services/cookies.js
Volatile computed properties are deprecated (https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_computed-property-volatile). These were only used internally, so they can safely be converted to methods.
These could also be implemented using `Object.defineProperty` to define ES5 getters, and I'm happy to do that if preferred, but I don't see what that extra code complexity buys us over just making them methods.
=> Remove volatile computed properties

tests/unit/clear-all-cookies-test.js, tests/unit/services/cookies-test.js
This moves the tests for the `clearAllCookies` test helper into their own test file instead of testing the helper in the unit test of the `cookies` service.
=> move test for test helper into own test file

.travis.yml, addon/services/cookies.js, testem.js, tests/unit/services/cookies-test.js
This adds Firefox to the browsers we test with in CI; see https://github.com/simplabs/ember-cookies/issues/152#issuecomment-377833332
It also includes a fix for a bug (or different behavior compared to Chrome) in Firefox: Firefox will set the default cookie path with a trailing slash (e.g. `/some/path/`) while Chrome would set it without the trailing slash (e.g. `/some/path`). In order to make the behavior the same for all browsers, this changes the `cookies` service so that it would automatically set a normalized default `path` (`/some/path` in the above example) if none was specified. I'm not really happy with this (as writing a cookie via the `cookies` service will now result in a different cookie than just using `document.cookie =`) but couldn't really think of a better solution 🤔
=> test in Firefox on CI

README.md, addon/utils/serialize-cookie.js, tests/unit/services/cookies-test.js
There is a new cookie attribute called SameSite that we may want to support as well.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Directives
```
`SameSite=Strict`
`SameSite=Lax` (Optional)
Allows servers to assert that a cookie ought not to be sent along with cross-site requests, which provides some protection against cross-site request forgery attacks (CSRF).
```
=> Add SameSite attribute support

.travis.yml, config/ember-try.js, package.json, yarn.lock
This fixes 2 problems with the Travis pipeline:
* currently, the deployment step runs for **all** environments which means we're deploying several times (which is likely not a huge problem as it's the same version each time anyway and subsequent deployments will fail anyways because of that) but we're also deploying if 1 test environment completes successfully while we actually want to wait for all of them; this moves the deployment to a separate stage that will only run once **all** test environments have succeeded
* we are currently only testing against the LTS releases from Ember's 2.x series; this adds the LTS releases from the 3.x series as well
=> Fix travis pipeline

addon/services/cookies.js, tests/unit/services/cookies-test.js
This handles the case that the `fastBoot` services does not exist which is the case in apps that do not use FastBoot.
closes #346
=> don't fail when fastBoot service does not exist

.travis.yml
…as it turns out
```yaml
on:
tags: true
```
is actually required: https://travis-ci.org/simplabs/ember-cookies/jobs/604619047#L557
=> Fix npm deployment for real

addon/services/cookies.js, tests/unit/services/cookies-test.js
The idea of the check was that a cookie that was written with the secure attribute should only be visible when the current location's protocol is `https:`. That is not actually correct though – according to [RFC 6265](https://tools.ietf.org/html/rfc6265#section-4.1.2.5), the `secure` attribute only controls whether the cookie is sent with secure (HTTPS) requests only or not which does not mean it cannot be accessible from non-secure locations. Chrome's behavior is different from Firefox' here but that's a matter of these browsers and not something we need to cover in the tests. The PR also removes the (wrong) implementation of the same mechanism from the FastBoot part of the addon (where a cookie with the secure flag was only visible when the request's protocol is `https:`).
=> Remove wrong implementation of secure attribute

README.md
We're currently listing `strict` and `lax` as supported values for the `sameSite` option although we don't actually check whether the passed in value is one of those two. Like that, the documentation is not helpful and people will have to go elsewhere to learn what the two values mean anyway. Now, there's also `SameSite=None` which we already support but the README says we don't.
Hence, simply removing the docs seems the best option.
closes #381
=> Remove example value for sameSite from README

package.json
This drops support for Node 8.
=> Drop support for Node 8

.github/workflows/ci.yml, addon-test-support/ember-cookies/clear-all-cookies.js, addon/services/cookies.js, config/ember-try.js, package.json, yarn.lock
This drops support for Ember versions < 3.0. It also removes the now unnecessary `ember-getowner-polyfill` and always uses `Object.assign` or Ember's `assign` instead of Ember's `merge` which has been deprecated.
=> Drop support for Ember versions < 3.0

package.json
This needs to be inside `ember-addon`, not `engines`
=> package.json: Fix `versionCompatibility` option

.github/workflows/ci.yml
The regular `yarn install` takes ~23sec. When using caching the cache download takes ~15sec, the `yarn install` then still takes ~13sec, and at the end of the job the cache upload takes another ~36sec. Ultimately this means that caching makes us significantly slower in this case.
=> CI: Remove yarn caching

testem.js
This matches https://github.com/ember-cli/ember-addon-output/blob/v3.21.2/testem.js plus headless Firefox support
=> Update `testem` config

package.json, yarn.lock
The missing ember-maybe-import-regenerator dependency (which apparently has been included in newer apps by default for some time) causes the ember-canary build to fail (or to not start at all so that eventually the GitHub Action times out).
=> add ember-maybe-import-regenerator dev dependency

.github/workflows/ci.yml, config/ember-try.js, package.json
As long as we support Ember 3.0 we won't be able to adopt native classes. Given that Ember 4.0 is around the corner, it seems fine to drop support for Ember 3.0 (although of course doing so is a breaking change). 3.4 is sufficient since we can use [ember-native-class-polyfill](https://github.com/pzuraq/ember-native-class-polyfill) to add support that.
=> Update minimum Ember version to 3.4

.github/workflows/ci.yml, package.json
Node 10 has reached EOL earlier this year and this drops support for it.
=> Drop support for Node 10

.github/workflows/ci.yml, .github/workflows/release.yml
Add `cache` to workflows using `actions/setup-node`
`setup-node` GitHub Action just released a new option to add cache to steps using it.
You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/
---
🤖 This PR has been generated automatically by [this octoherd script](https://github.com/oscard0m/octoherd-script-add-cache-to-node-github-action), feel free to run it in your GitHub user/org repositories! 💪🏾
=> ci(workflow): add cache to workflows using actions/setup-node

.github/workflows/ci.yml, config/ember-try.js
This adds the most recent Ember LTS release 3.24 to our testing matrix.
=> Add recent ember lts to test matrix

.renovaterc.json
This adds configuration for Renovate. We group all non-major `devDependencies` updates into one PR per week to reduce noise.
=> add renovate configuration

config/ember-try.js
This fixes CI by adding the ember-auto-import@^2.2.3 dependency to the ember-release scenario – Ember 4 requires ember-auto-import@2.
=> Add ember-auto-import@^2.2.3 dependency to ember-release scenario

.github/workflows/ci.yml, config/ember-try.js
This adds an ember-try scenario for Ember 3.28 which is the last LTS before 4.0 to our testing matrix.
=> Add Ember 3.28 scenario

.babelrc.js, .eslintrc.js, .npmignore, package.json, yarn.lock
These are necessary changes to have CI pass in addition to #701.
=> Adjust ESLint config to work with v8

config/ember-try.js, package.json, yarn.lock
Currently, running `ember test` in local fails due to missing `ember-auto-import@2` and `webpack` dependencies.
This makes local development or running tests cumbersome as you either need to run ember-try scenario (which is slow) or add deps manually (which is just inconvenient).
=> Add ember-auto-import@2 and webpack dev deps

.github/workflows/ci.yml
Syncs with latest addon blueprint, per https://github.com/ember-cli/ember-cli/pull/9697
This uses Github Action's
[concurrency](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency)
feature to kill the workflow runs of commits that are not the current
head commit of a PR.  `head_ref` is only set for PRs
[source](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context),
which is why we fall back to `ref` (so push workflows will run one job
for each branch for the most recent commit).
=> feat: cancel stale actions workflows

.github/workflows/ci.yml, .github/workflows/release.yml, packages/ember-cookies/package.json, packages/test-app/package.json
#747 is a breaking change hence it might be good time to land this as well cc @marcoow
=> chore!: drop Node.js 12 support

packages/test-app/package.json
Fixes
```
(node:11219) UnhandledPromiseRejectionWarning: Error: Unable to require module 'crypto' because it was not in the whitelist.
at Object.require (/Users/bobrystoteles/Projects/oss/ember-cookies/node_modules/fastboot/src/fastboot-schema.js:191:15)
at Module.callback (/Users/bobrystoteles/Projects/oss/ember-cookies/packages/test-app/dist/assets/addon-tree-output/@ember-data/store/index-8b77b852.js:509:1)
at Module.exports (/Users/bobrystoteles/Projects/oss/ember-cookies/packages/test-app/dist/assets/vendor/loader/loader.js:106:1)
at Module._reify (/Users/bobrystoteles/Projects/oss/ember-cookies/packages/test-app/dist/assets/vendor/loader/loader.js:143:1)
at Module.reify (/Users/bobrystoteles/Projects/oss/ember-cookies/packages/test-app/dist/assets/vendor/loader/loader.js:130:1)
at …
```
=> chore: add crypto and node-fetch to fastbootDependencies

packages/test-app/package.json, yarn.lock
- v5 ember requires `@ember/string` to be an explicit dependency.
=> chore: add @ember/string to the test-app

.bowerrc
- removes .bowerrc
It raises warning when running the ember server
=> chore: remove .bowerrc

.github/workflows/ci.yml, .github/workflows/release.yml, package.json, packages/ember-cookies/package.json, packages/test-app/package.json
https://github.com/nodejs/release#release-schedule
Node 14 has reached its EOL
Node 16 will reach it later this year our minimal supported version
=> chore: Drop node - set minimal node version to >=16

.github/workflows/ci.yml
Adds `ember-default` scenario to CI.
This will make sure that the default package.json packages are not broken.
=> chore: run ember-default scenario in CI

packages/test-app/package.json, yarn.lock
- it's unmaintained and it breaks for v5
=> chore: remove ember-export-application-global

packages/ember-cookies/src/services/cookies.js, packages/ember-cookies/src/test-support/clear-all-cookies.js
- removes @ember/polyfills's `assign` method
inherently drops IE11 support
=> feat(breaking): replace polyfills assign with Object.assign

.github/workflows/ci.yml
- stops officially supported ember versions from being cancelled when `beta`,  `canary` channels fail.
=> chore(ci): don't halt jobs on failure

.github/workflows/ci.yml, packages/ember-cookies/package.json, packages/test-app/config/ember-try.js
- Drops Ember v3 support
- Starts testing Ember 4.0 the earliest.
=> feat(breaking): drop Ember v3 versions

CHANGELOG.md, package.json, packages/ember-cookies/package.json, packages/test-app/package.json
- sets ember-cookies version to 1.0.0
- decreases versions for test-app and monorepo to 0.1.0. They are not a part of the release and don't need to match.
This should make versioning less confusing.
Will create a tag and release after the merge.
=> chore(release): ember-cookies v1.0.0

.github/workflows/ci.yml
- Adds https://github.com/mainmatter/continue-on-error-comment
- Sets `embroider-optimized`, `ember-canary` and `ember-beta` scenario to allow failure.
"ember-optimized" fails due to Fastboot https://github.com/mainmatter/ember-cookies/issues/833
Works just fine on regular apps.
=> chore(ci): add Mainmatter/continue-on-error action

packages/ember-cookies/index.d.ts
ClearAllCookies method was not exported as default.
But the type mistakenly exported as default the Pr fix the type.
=> Fix type export of clearAllCookies

.github/workflows/ci.yml
- Changes the CI trigger event from `pull_request` to `pull_request_target` so the action can create comments on PRs coming from forks.
Also limits the permissions for that workflow as per guides
https://github.com/mainmatter/continue-on-error-comment/releases/tag/v1.2
=> chore(ci): use pull_request_target event to allow continue-on-error-comment to work for forks

package.json, packages/ember-cookies/src/utils/serialize-cookie.js, packages/test-app/package.json, packages/test-app/tests/unit/services/cookies-test.js, pnpm-lock.yaml
Adds support for Partitioned Cookies. Useful for third party cookies. See https://developer.mozilla.org/en-US/docs/Web/Privacy/Privacy_sandbox/Partitioned_cookies
=> Support Partitioned Cookies
